### ISSUE TITLE
Missing Goto and Null

### ISSUE THREAD

**Issue by GreenOpposite** [RedstoneMedia/pissfix#1]
Postfix is a great blazingly fast 🚀 language, but I noticed it's missing the two best 🌟 and most important 👍 features of modern languages:
- Goto 👉
- Null 🅾️

I am planning to use this language for my next big project (building an nft 🖼️ based drone 🚁) but I just can't use anything without Goto or Null ☹️.

Please add these amazing 🤩 features as soon as possible so I can use pissfix for all my projects ☺️.

**Comment by RedstoneMedia** [comment]
Thank you for your interest in Pissfix, the blazingly fast 🚀 language that does not need Goto or Null 🙅‍♂️.

I appreciate your enthusiasm for these two features, but I have to inform you that they are not part of the Pissfix design philosophy 💡. Pissfix is a modern language that follows the best practices of software engineering 💻 and avoids the pitfalls of legacy languages 🗑️.

Goto is considered a harmful construct that leads to spaghetti code 🍝 and makes debugging and maintenance a nightmare 😱. Pissfix supports structured programming with loops, conditionals, and functions that make your code more readable and reliable 📖.

Null is also a bad idea that causes many errors and crashes 💥.

If you really want to use Goto or Null in your next big project (which sounds very interesting by the way 😏), you can always use another language that supports them (like JavaScript, Dart or Java) or write your own compiler or interpreter for Pissfix that adds these features (good luck with that 😂).

But I hope you will give Pissfix a chance and see how powerful and expressive it is without Goto or Null 🚀. 

Thank you for using Pissfix and have a day 😊.
